# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 738ab83163b2e210ab3080305a82f266b1a896f7b433d2820213078b190fcd0c47649b12401da23a30c3c938b7a8669da7091ab6dba65fec5ba4814db6bb66a9

test:
  secret_key_base: 9bbc3cf19554ecc80abf82607a68f36c2c4a477af42e9684a9dd11a78a8cadbcf2c0a44e982df3c6a2cadb79501c0d8c05b1d645c28d9d1099ca8425418304a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
